import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';import{spawnSync}from'node:child_process';
const here=path.dirname(fileURLToPath(import.meta.url)),source=fs.readFileSync(path.join(here,'../src/recomp/gen/recomp_frontend_callbacks.c'),'utf8'),crt=fs.readFileSync(path.join(here,'../src/recomp/gen/recomp_0014.c'),'utf8'),manual=fs.readFileSync(path.join(here,'../src/recomp_manual.c'),'utf8'),stubs=fs.readFileSync(path.join(here,'../src/recomp/gen/recomp_stubs_unresolved.c'),'utf8');
const xbe=fs.readFileSync(path.join(here,'../../default.xbe')),sections=xbe.readUInt32LE(0x11C),table=xbe.readUInt32LE(0x120)-xbe.readUInt32LE(0x104);
function original(va,size){for(let i=0;i<sections;++i){const p=table+i*56,start=xbe.readUInt32LE(p+4),n=xbe.readUInt32LE(p+16);if(va>=start&&va+size<=start+n){const offset=xbe.readUInt32LE(p+12)+va-start;return xbe.subarray(offset,offset+size);}}throw Error('Original bytes unavailable');}
function body(text,va){const h=va.toString(16).toUpperCase().padStart(8,'0'),m=text.match(new RegExp(`^void sub_${h}\\(void\\)\\r?\\n\\{[\\s\\S]*?^\\}`,'m'));assert(m);return m[0];}
const fixture=body(crt,0x13F82A)+'\n'+[0x13E6CF,0x1933D0,0xE0510].map(va=>body(source,va)).join('\n');
const asm=fs.readFileSync(path.join(here,'../../disasm-seeded/asm/text.asm'),'utf8'),decoded=[...asm.matchAll(/^\s*0x([0-9A-Fa-f]+)[ \t]+([0-9a-f]+)[ \t]+(\w+)[ \t]+(.*?)\r?$/gm)].map(m=>({va:parseInt(m[1],16),bytes:Buffer.from(m[2],'hex')}));
let instructions=0,total=0;for(const[start,end]of[[0x1933D0,0x193454],[0xE0510,0xE0581],[0x13F82A,0x13F84B]]){let cursor=start;for(const{va,bytes}of decoded){if(va<start||va>=end)continue;assert.equal(va,cursor);assert.deepEqual(original(va,bytes.length),bytes);cursor+=bytes.length;total+=bytes.length;++instructions;}assert.equal(cursor,end);}
// Missing disassembly range independently decoded directly from original XBE
// by Capstone:19 instructions,49bytes at13E6CF..13E700.
const raw=Buffer.from('833df09b250001568b7424087e0c6a0156e8451100005959eb0ca1e89b25000fb6047083e00185c08d462075028bc65ec3','hex');assert.deepEqual(original(0x13E6CF,raw.length),raw);assert.equal(raw.length,49);instructions+=19;total+=49;
assert(!/^void sub_0013E6CF/m.test(stubs));for(const va of[0x1933D0,0x13E6CF,0xE0510]){const h=va.toString(16).toUpperCase().padStart(8,'0');assert(manual.includes(`if (xbox_va == 0x${h}u) return sub_${h};`));}
for(const m of fixture.matchAll(/PUSH32\(esp, 0x([0-9A-F]+)u\); sub_([0-9A-F]+)\(\);/g)){const ret=parseInt(m[1],16),raw=original(ret-5,5);assert.equal(raw[0],0xE8);assert.equal((ret+raw.readInt32LE(1))>>>0,parseInt(m[2],16));}
assert.equal(original(0x259BE8,4).readUInt32LE(),0x238B08);assert.equal(original(0x259BF0,4).readUInt32LE(),1);
const originalTable=`static const uint8_t original_ctype[]={${[...original(0x238B06,514)]}};\n`;
console.log(`PASS ${instructions} original instructions/${total} bytes, actual CRT classification table and original direct call PCs`);
const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'dah-frontend-lower-'));
function test(label,text,status){const dir=path.join(temporary,label);fs.mkdirSync(dir);fs.writeFileSync(path.join(dir,'frontend_lower_fixture.inc'),text);fs.writeFileSync(path.join(dir,'lower_original_table.inc'),originalTable);const exe=path.join(dir,'test.exe'),build=spawnSync('cl.exe',['/nologo','/W4','/WX','/O2','/std:c11',`/I${dir}`,`/Fe:${exe}`,`/Fo:${path.join(dir,'test.obj')}`,path.join(here,'test_frontend_lower.c')],{cwd:dir,encoding:'utf8',timeout:30000});assert.equal(build.status,0,build.stdout+build.stderr);const run=spawnSync(exe,[],{cwd:dir,encoding:'utf8',timeout:30000});assert.equal(run.status,status,run.stdout+run.stderr);console.log(status?`PASS negative control ${label}: ${run.stderr.trim()}`:run.stdout.trim());}
test('production',fixture,0);test('identity-stub',fixture.replace('eax = eax != 0u ? esi + 0x20u : esi;','eax = esi;'),1);test('wrong-character-cleanup',fixture.replace('esp += 4u; /* cdecl RET; caller owns character argument */','esp += 8u;'),1);test('late-buffer-flush',fixture.replace('if (eax >= ecx)','if (eax > ecx)'),1);test('wrong-empty-result-count',fixture.replace('eax = 1u;\n    POP32(esp, esi);','eax = 0u;\n    POP32(esp, esi);'),1);test('wrong-mode-zero',fixture.replace('0x80000001u','0x80000000u'),1);
console.log(`TEST_OUTPUT ${temporary}`);
